version: '3.8'

networks:
 default:
   external: false
   name: GraphQL-networks

services:

  postgres:
   image: "postgres:13-alpine"
   command: postgres -c 'max_connections=1000'
   restart: always
   container_name: postgresql
   environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_DB=invoice_db
   volumes:
     - ./db_data:/var/lib/postgresql/data
   ports:
     - "5432:5432"